# Dockerfile to create image for use with 'act' tool (testing GitHub actions)
FROM catthehacker/ubuntu:runner-latest

# Install required tools
RUN sudo apt-get update && sudo apt-get install -y maven
