# Ubuntu base image useful for testing builds and running DD Photos.  See Appendix A
# of README-DEV.md for details on how to use this Dockerfile.
FROM ubuntu

# Install helpful tools, java, maven
RUN apt-get update && apt-get install -y \
    x11-apps \
    iputils-ping nmap telnet \
    git vim tree \
    openjdk-25-jdk maven

# Set JAVA_HOME to avoid warnings (Unable to autodetect 'javac' path)
ENV JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64

# Start bash
CMD ["/bin/bash"]
