# Overrides for Doug's development environments

settings.debug.enabled= true

# change starting size (set to size used for screenshots, 1500x981)
settings.debug.changesize=true

# use local 'ddphotos' image
#settings.debug.local.image=true

# turn on screenshot menu item
settings.debug.screenshots=true
settings.debug.screenshots.path=/Users/donohoe/work/ddphotos-app/images/screenshots
settings.debug.screenshots.shadow=true