##
## Command line log4j2.properties
##

rootLogger.level = WARN
rootLogger.appenderRef.console.ref = ConsoleAppender

# Define a NullAppender to effectively disable logging by setting .ref to NullAppender
appender.nullAppender.name = NullAppender
appender.nullAppender.type = Null

# Console Appender Configuration
appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy/MMM/dd kk:mm:ss.SSS} CLI [%-15.15t::%-25.25c] %-5p %m%n

# Specific customizations
logger.donohoedigital.name = com.donohoedigital
logger.donohoedigital.level = DEBUG

logger.matchingresources.name = com.donohoedigital.config.MatchingResources
logger.matchingresources.level = INFO
