##
## Plain output alternate to command line log4j2.properties
##

rootLogger.level = DEBUG
appender.console.layout.pattern = %m%n

# Specific customizations
logger.donohoedigitalconfig.name = com.donohoedigital.config
logger.donohoedigitalconfig.level = WARN
