##
## Default log4j2.properties
##

rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender

# Console Appender Configuration
appender.console.name = ConsoleAppender
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy/MMM/dd kk:mm:ss.SSS} DEF [%-15.15t::%-25.25c] %-5p %m%n

# Specific customizations
logger.donohoedigital.name = com.donohoedigital
logger.donohoedigital.level = DEBUG

logger.matchingresources.name = com.donohoedigital.config.MatchingResources
logger.matchingresources.level = INFO
